begin;
select plan(39);

select has_extension('postgis', 'PostGIS is installed');
select has_table('public', 'profiles', 'profiles exists');
select has_table('public', 'plans', 'plans exists');
select has_table('public', 'plan_members', 'plan_members exists');
select has_table('public', 'successful_meets', 'successful_meets exists');
select has_table('public', 'forming_groups', 'forming groups exists');
select has_table('public', 'forming_group_members', 'forming group members exist');
select has_function('public', 'discover_nearby_plans', array['double precision', 'double precision', 'integer', 'timestamp with time zone', 'timestamp with time zone'], 'discovery RPC exists');
select has_function('public', 'join_plan', array['uuid'], 'join RPC exists');
select has_function('public', 'leave_plan', array['uuid'], 'leave RPC exists');
select has_function('public', 'cancel_plan', array['uuid'], 'cancel plan RPC exists');
select has_function('public', 'complete_onboarding', array['text', 'date', 'text', 'text[]'], 'onboarding RPC exists');
select has_function('public', 'create_plan', array['text', 'timestamp with time zone', 'text', 'text', 'double precision', 'double precision', 'integer', 'text', 'text'], 'create plan RPC exists');
select has_function('public', 'get_plan_detail', array['uuid'], 'plan detail RPC exists');
select has_function('public', 'get_my_plan_chats', array[]::text[], 'chat summary RPC exists');
select has_function('public', 'block_user', array['uuid'], 'block RPC exists');
select has_function('public', 'report_target', array['text', 'uuid', 'text', 'text'], 'report RPC exists');
select has_function('public', 'create_availability_intent', array['timestamp with time zone', 'double precision', 'double precision', 'integer', 'text[]'], 'availability creation RPC exists');
select has_function('public', 'recommend_plans_for_intent', array['uuid'], 'intent recommendation RPC exists');
select has_function('public', 'find_compatible_intents', array['uuid'], 'compatible intent RPC exists');
select has_function('public', 'create_forming_group', array['uuid'], 'forming group creation RPC exists');
select has_function('public', 'get_my_forming_group', array[]::text[], 'forming group inbox RPC exists');
select has_function('public', 'respond_to_forming_group', array['uuid', 'boolean'], 'forming group response RPC exists');
select has_function('public', 'check_in', array['uuid', 'double precision', 'double precision'], 'check-in RPC exists');
select has_function('public', 'get_plan_check_in_status', array['uuid'], 'check-in status RPC exists');
select has_function('public', 'get_my_meet_stats', array[]::text[], 'meet stats RPC exists');
select has_function('public', 'accept_community_terms', array['text'], 'community terms RPC exists');
select has_function('public', 'delete_my_account', array[]::text[], 'account deletion RPC exists');
select has_function('public', 'review_report', array['uuid', 'report_status'], 'moderation review RPC exists');
select has_column('public', 'profiles', 'terms_accepted_at', 'terms acceptance is recorded');
select has_column('public', 'reports', 'moderation_due_at', 'reports have a 24-hour deadline');
select has_trigger('public', 'plans', 'plans_approximate_location', 'plan coordinates are approximated');
select has_trigger('public', 'plan_messages', 'plan_messages_moderate_ugc', 'chat content is filtered');
select row_security_active('public.profiles'::regclass), 'profiles RLS is active';
select row_security_active('public.plans'::regclass), 'plans RLS is active';
select row_security_active('public.availability_intents'::regclass), 'private intents RLS is active';
select row_security_active('public.forming_groups'::regclass), 'forming groups RLS is active';
select row_security_active('public.forming_group_members'::regclass), 'forming group members RLS is active';
select row_security_active('public.ai_usage_logs'::regclass), 'AI usage RLS is active';

select * from finish();
rollback;
