import { getLocales } from 'expo-localization';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const deviceLanguage = getLocales()[0]?.languageCode;

// eslint-disable-next-line import/no-named-as-default-member
void i18n.use(initReactI18next).init({
  compatibilityJSON: 'v4',
  fallbackLng: 'en',
  lng: deviceLanguage === 'it' || deviceLanguage === 'zh' ? deviceLanguage : 'en',
  interpolation: { escapeValue: false },
  resources: {
    en: { translation: { now: 'Now', map: 'Map', create: 'Create', chats: 'Orbits', me: 'Me', tryAgain: 'Try again', home: { nearby: 'Nearby now', hero: 'Meet people.\nDo something. Now.', subtitle: 'Spontaneous plans nearby, for the next six hours.', free: "I'm free", forming: "See what's forming nearby", plans: 'Plans near you', seeMap: 'See map' }, location: { title: 'Find plans around you', privacy: 'HAO uses your area only for distance and nearby search. People never see your live location.', use: 'Use my location', retry: 'Try location again', settings: 'Open settings', manual: 'or browse without location' }, orbit: { eyebrow: 'ORBIT', title: 'Your circles', subtitle: "Coordinate plans you're attending.", loadError: "Orbits couldn't load", emptyTitle: 'No active Orbits yet', emptyBody: 'Attend a nearby plan to open a temporary group.', discover: "See what's happening", chatReady: 'Plan chat is ready' }, profile: { title: 'Me', demoMode: 'Testing channel · browse-only', activityTitle: 'Your real-world activity', activityNotRecorded: 'Activity is not recorded in test mode.', statsLoadError: 'Activity could not load. Please try again.', successfulMeets: 'Successful Meets', plansCheckedIn: 'Plans checked in', meetExplanation: 'A Successful Meet requires at least two valid check-ins and a completed plan.', accountPrivacy: 'Account and privacy', deleteDescription: 'Deleting your account permanently removes your profile and associated personal data.', deleteAccount: 'Delete account', deleting: 'Deleting…', exitTest: 'Exit test mode', signOut: 'Sign out', deleteTitle: 'Delete account?', deleteBody: 'This permanently deletes your HAO account, profile, messages, memberships, and activity. This cannot be undone.', cancel: 'Cancel', deleteConfirm: 'Delete permanently', deleteError: 'Your account could not be deleted. Please try again.' } } },
    it: { translation: { now: 'Ora', map: 'Mappa', create: 'Crea', chats: 'Gruppi', me: 'Profilo', tryAgain: 'Riprova', home: { nearby: 'Vicino a te', hero: 'Incontra persone.\nFai qualcosa. Ora.', subtitle: 'Programmi spontanei nelle vicinanze per le prossime sei ore.', free: 'Sono libero', forming: 'Scopri cosa si sta formando', plans: 'Programmi vicino a te', seeMap: 'Vedi mappa' }, location: { title: 'Trova programmi vicino a te', privacy: 'HAO usa solo la tua zona per distanza e ricerca. Nessuno vede la tua posizione in tempo reale.', use: 'Usa la mia posizione', retry: 'Riprova posizione', settings: 'Apri impostazioni', manual: 'oppure esplora senza posizione' }, orbit: { eyebrow: 'GRUPPI', title: 'I tuoi gruppi', subtitle: 'Organizza i programmi a cui partecipi.', loadError: 'Impossibile caricare i gruppi', emptyTitle: 'Nessun gruppo attivo', emptyBody: 'Partecipa a un programma vicino per aprire un gruppo temporaneo.', discover: 'Scopri cosa succede', chatReady: 'La chat del programma è pronta' }, profile: { title: 'Profilo', demoMode: 'Canale di prova · sola navigazione', activityTitle: 'La tua attività nel mondo reale', activityNotRecorded: 'Le attività non vengono registrate in modalità di prova.', statsLoadError: 'Impossibile caricare le attività. Riprova.', successfulMeets: 'Incontri riusciti', plansCheckedIn: 'Programmi con check-in', meetExplanation: 'Un incontro riuscito richiede almeno due check-in validi e un programma completato.', accountPrivacy: 'Account e privacy', deleteDescription: 'Eliminando il tuo account rimuoverai definitivamente il profilo e i dati personali associati.', deleteAccount: 'Elimina account', deleting: 'Eliminazione…', exitTest: 'Esci dalla modalità di prova', signOut: 'Esci', deleteTitle: 'Eliminare l’account?', deleteBody: 'Questa azione elimina definitivamente il tuo account HAO, il profilo, i messaggi, le partecipazioni e le attività. Non può essere annullata.', cancel: 'Annulla', deleteConfirm: 'Elimina definitivamente', deleteError: 'Impossibile eliminare l’account. Riprova.' } } },
    zh: { translation: { now: '现在', map: '地图', create: '创建', chats: '群聊', me: '我的', tryAgain: '重试', home: { nearby: '附近动态', hero: '认识新朋友。\n现在就出发。', subtitle: '发现附近六小时内的即时活动。', free: '我有空', forming: '看看附近正在组什么局', plans: '附近计划', seeMap: '查看地图' }, location: { title: '查找附近计划', privacy: 'HAO 只使用大致区域计算距离和搜索，其他人永远看不到你的实时位置。', use: '使用我的位置', retry: '重试定位', settings: '打开设置', manual: '或不使用定位直接浏览' }, orbit: { eyebrow: '群聊', title: '你的群聊', subtitle: '协调你正在参加的计划。', loadError: '群聊暂时无法加载', emptyTitle: '暂无进行中的群聊', emptyBody: '参加附近的计划后，会自动建立临时群聊。', discover: '看看附近有什么', chatReady: '计划群聊已开启' }, profile: { title: '我的', demoMode: '测试模式 · 仅供浏览', activityTitle: '你的线下活动', activityNotRecorded: '测试模式不会记录活动数据。', statsLoadError: '活动数据暂时无法加载，请重试。', successfulMeets: '成功见面', plansCheckedIn: '已签到计划', meetExplanation: '“成功见面”需要至少两名成员有效签到，且计划已完成。', accountPrivacy: '账号与隐私', deleteDescription: '删除账号会永久移除你的个人资料及相关个人数据。', deleteAccount: '删除账号', deleting: '正在删除…', exitTest: '退出测试模式', signOut: '退出登录', deleteTitle: '删除账号？', deleteBody: '此操作会永久删除你的 HAO 账号、个人资料、消息、成员记录和活动数据，且无法恢复。', cancel: '取消', deleteConfirm: '永久删除', deleteError: '无法删除账号，请重试。' } } },
  },
});

i18n.addResourceBundle('en', 'translation', {
  auth: { tagline: 'Meet people.\nDo something. Now.', subtitle: 'Spontaneous plans nearby. No endless feed, just a reason to step outside.', testPreview: 'TEST PREVIEW', demoTitle: "See what's happening nearby", demoBody: 'No account needed. Explore HAO safely in test mode.', enterTest: 'Enter test mode', accountSignIn: 'Account sign in', continueApple: 'Continue with Apple', continueGoogle: 'Continue with Google', setupRequired: ' · Setup required', email: 'Email', phone: 'Phone', emailHelp: 'Use your email for this web test.', phoneHelp: 'Enter your phone number with country code.', emailAddress: 'Email address', phoneNumber: 'Phone number', verificationCode: 'Verification code', codePlaceholder: '6-digit code', verifyContinue: 'Verify and continue', sendCode: 'Send code', differentEmail: 'Use a different email', differentNumber: 'Use a different number', ageRequirement: 'You must be 18 or older to use HAO.', emailSent: 'Check your email for the sign-in code or link.', phoneSent: 'Verification code sent.', sendError: 'The code could not be sent. Please try again.', verifyError: 'The code could not be verified. Please try again.', socialError: 'Sign-in could not be completed.' },
  onboarding: { title: 'Tell us about you', subtitle: 'This keeps nearby plans relevant and the community 18+.', displayName: 'Display name', birthDate: 'Birth date', birthDatePlaceholder: 'Birth date · YYYY-MM-DD', primaryLanguage: 'Primary language', chooseInterests: 'Choose 3–5 interests', terms: "I agree to HAO's Community Terms: zero tolerance for abusive, hateful, sexual, threatening, or unsafe content. Reports may lead to removal or suspension.", enter: 'Enter HAO', termsError: 'The community terms could not be accepted. Please try again.', profileError: 'Your profile could not be completed. Please review the details.', interestsError: 'Interests could not load. Please try again.' },
  createPlan: { title: 'Host a plan', subtitle: 'Keep it simple, public, and soon.', activity: 'What do you want to do?', when: 'When?', in30: 'In 30 min', in1h: 'In 1 hour', in2h: 'In 2 hours', tonight: 'Tonight', publicPlace: 'Public meeting place', placeHelp: 'Choose a real café, park, or other well-lit public place. HAO shows only an approximate 400 m meeting area until verified venue search is connected.', venueName: 'Venue name', venueAddress: 'Address (optional)', groupSize: 'Group size', decrease: 'Decrease group size', increase: 'Increase group size', people_one: '{{count}} person', people_other: '{{count}} people', addNote: 'Add a note', planNote: 'Plan note', optionalDetails: 'Optional details', host: 'Host this plan', createError: 'The plan could not be created. Please review the details and try again.', activitiesError: 'Activities could not load. Please try again.' },
  freeScreen: { back: 'Back', backNow: 'Back to Now', cancel: 'Cancel', title: "I'm Free", subtitle: 'Tell HAO what works right now. This availability expires automatically.', duration: 'For how long?', min30: '30 min', hour1: '1 hour', hours2: '2 hours', tonight: 'Tonight', interests: 'What sounds good?', distance: 'How far?', locationPrivacy: 'Your raw location is never shown to other people.', submit: "See what's forming", activeTitle: "You're in Now mode", activeUntil: 'Until {{time}}. Your exact location stays private.', formingNearby: 'Forming near you', nothingYet: 'Nothing is forming yet', peopleFree: '{{count}} people nearby are also free{{interest}}.', firstHost: "Be the first Host in this area. We won't invent activity around you.", hostPlan: 'Host a plan', change: 'Change availability', error: 'Availability could not be saved. Please try again.' },
}, true, true);

i18n.addResourceBundle('it', 'translation', {
  auth: { tagline: 'Incontra persone.\nFai qualcosa. Ora.', subtitle: 'Programmi spontanei vicino a te. Nessun feed infinito, solo un motivo per uscire.', testPreview: 'ANTEPRIMA DI PROVA', demoTitle: 'Scopri cosa succede vicino a te', demoBody: 'Non serve un account. Esplora HAO in sicurezza nella modalità di prova.', enterTest: 'Entra in modalità di prova', accountSignIn: 'Accedi al tuo account', continueApple: 'Continua con Apple', continueGoogle: 'Continua con Google', setupRequired: ' · Configurazione richiesta', email: 'Email', phone: 'Telefono', emailHelp: 'Usa la tua email per questa prova web.', phoneHelp: 'Inserisci il numero con il prefisso internazionale.', emailAddress: 'Indirizzo email', phoneNumber: 'Numero di telefono', verificationCode: 'Codice di verifica', codePlaceholder: 'Codice a 6 cifre', verifyContinue: 'Verifica e continua', sendCode: 'Invia codice', differentEmail: 'Usa un’altra email', differentNumber: 'Usa un altro numero', ageRequirement: 'Devi avere almeno 18 anni per usare HAO.', emailSent: 'Controlla l’email per il codice o il link di accesso.', phoneSent: 'Codice di verifica inviato.', sendError: 'Impossibile inviare il codice. Riprova.', verifyError: 'Impossibile verificare il codice. Riprova.', socialError: 'Impossibile completare l’accesso.' },
  onboarding: { title: 'Parlaci di te', subtitle: 'Così manteniamo pertinenti i programmi vicini e la community riservata ai maggiorenni.', displayName: 'Nome visualizzato', birthDate: 'Data di nascita', birthDatePlaceholder: 'Data di nascita · AAAA-MM-GG', primaryLanguage: 'Lingua principale', chooseInterests: 'Scegli 3–5 interessi', terms: 'Accetto i Termini della community HAO: tolleranza zero per contenuti offensivi, d’odio, sessuali, minacciosi o non sicuri. Le segnalazioni possono portare alla rimozione o sospensione.', enter: 'Entra in HAO', termsError: 'Impossibile accettare i termini della community. Riprova.', profileError: 'Impossibile completare il profilo. Controlla i dati.', interestsError: 'Impossibile caricare gli interessi. Riprova.' },
  createPlan: { title: 'Crea un programma', subtitle: 'Semplice, pubblico e a breve.', activity: 'Cosa vuoi fare?', when: 'Quando?', in30: 'Tra 30 min', in1h: 'Tra 1 ora', in2h: 'Tra 2 ore', tonight: 'Stasera', publicPlace: 'Luogo pubblico di incontro', placeHelp: 'Scegli un vero bar, parco o altro luogo pubblico ben illuminato. Finché la ricerca dei luoghi non sarà verificata, HAO mostra solo un’area approssimativa di 400 m.', venueName: 'Nome del luogo', venueAddress: 'Indirizzo (facoltativo)', groupSize: 'Dimensione del gruppo', decrease: 'Riduci il gruppo', increase: 'Aumenta il gruppo', people_one: '{{count}} persona', people_other: '{{count}} persone', addNote: 'Aggiungi una nota', planNote: 'Nota del programma', optionalDetails: 'Dettagli facoltativi', host: 'Crea questo programma', createError: 'Impossibile creare il programma. Controlla i dati e riprova.', activitiesError: 'Impossibile caricare le attività. Riprova.' },
  freeScreen: { back: 'Indietro', backNow: 'Torna a Ora', cancel: 'Annulla', title: 'Sono libero', subtitle: 'Dì a HAO cosa ti va di fare adesso. La disponibilità scade automaticamente.', duration: 'Per quanto tempo?', min30: '30 min', hour1: '1 ora', hours2: '2 ore', tonight: 'Stasera', interests: 'Cosa ti va?', distance: 'Quanto lontano?', locationPrivacy: 'La tua posizione esatta non viene mai mostrata agli altri.', submit: 'Scopri cosa si sta formando', activeTitle: 'Sei in modalità Ora', activeUntil: 'Fino alle {{time}}. La tua posizione esatta resta privata.', formingNearby: 'In formazione vicino a te', nothingYet: 'Non si sta ancora formando nulla', peopleFree: 'Anche {{count}} persone vicine sono libere{{interest}}.', firstHost: 'Crea il primo programma in questa zona. Non inventeremo attività inesistenti.', hostPlan: 'Crea un programma', change: 'Modifica disponibilità', error: 'Impossibile salvare la disponibilità. Riprova.' },
}, true, true);

i18n.addResourceBundle('zh', 'translation', {
  auth: { tagline: '认识新朋友。\n现在就出发。', subtitle: '发现附近的即时计划。没有刷不完的信息流，只有一个出门的理由。', testPreview: '测试预览', demoTitle: '看看附近正在发生什么', demoBody: '无需账号，即可在测试模式中安全体验 HAO。', enterTest: '进入测试模式', accountSignIn: '账号登录', continueApple: '使用 Apple 继续', continueGoogle: '使用 Google 继续', setupRequired: ' · 尚未配置', email: '邮箱', phone: '手机', emailHelp: '网页测试可使用邮箱登录。', phoneHelp: '请输入包含国家区号的手机号。', emailAddress: '邮箱地址', phoneNumber: '手机号码', verificationCode: '验证码', codePlaceholder: '6 位验证码', verifyContinue: '验证并继续', sendCode: '发送验证码', differentEmail: '使用其他邮箱', differentNumber: '使用其他号码', ageRequirement: '必须年满 18 岁才能使用 HAO。', emailSent: '请查看邮箱中的登录验证码或链接。', phoneSent: '验证码已发送。', sendError: '验证码发送失败，请重试。', verifyError: '验证码验证失败，请重试。', socialError: '登录未能完成，请重试。' },
  onboarding: { title: '介绍一下你自己', subtitle: '这些信息能让附近计划更适合你，并确保社区仅限成年人。', displayName: '显示名称', birthDate: '出生日期', birthDatePlaceholder: '出生日期 · 年年年年-月月-日日', primaryLanguage: '主要语言', chooseInterests: '选择 3–5 个兴趣', terms: '我同意 HAO 社区条款：对辱骂、仇恨、色情、威胁或危险内容零容忍；违规举报可能导致内容删除或账号停用。', enter: '进入 HAO', termsError: '无法接受社区条款，请重试。', profileError: '无法完成个人资料，请检查填写内容。', interestsError: '兴趣列表暂时无法加载，请重试。' },
  createPlan: { title: '发起计划', subtitle: '保持简单、公开，并尽快开始。', activity: '你想做什么？', when: '什么时候？', in30: '30 分钟后', in1h: '1 小时后', in2h: '2 小时后', tonight: '今晚', publicPlace: '公共见面地点', placeHelp: '请选择真实的咖啡馆、公园或其他照明良好的公共场所。在接入经过验证的场所搜索前，HAO 只显示约 400 米范围的模糊区域。', venueName: '场所名称', venueAddress: '地址（选填）', groupSize: '参与人数', decrease: '减少参与人数', increase: '增加参与人数', people: '{{count}} 人', addNote: '添加说明', planNote: '计划说明', optionalDetails: '补充信息（选填）', host: '发布这个计划', createError: '计划创建失败，请检查填写内容后重试。', activitiesError: '活动列表暂时无法加载，请重试。' },
  freeScreen: { back: '返回', backNow: '返回首页', cancel: '取消', title: '我有空', subtitle: '告诉 HAO 你现在想做什么；这段空闲状态会自动过期。', duration: '你有多长时间？', min30: '30 分钟', hour1: '1 小时', hours2: '2 小时', tonight: '今晚', interests: '想做什么？', distance: '多远以内？', locationPrivacy: '你的精确位置永远不会展示给其他人。', submit: '看看附近正在组什么局', activeTitle: '已进入即时模式', activeUntil: '有效至 {{time}}，你的精确位置会保持私密。', formingNearby: '附近正在组局', nothingYet: '附近暂时还没有计划', peopleFree: '附近还有 {{count}} 人有空{{interest}}。', firstHost: '成为这个区域第一个发起人；HAO 不会虚构附近活动。', hostPlan: '发起计划', change: '修改空闲状态', error: '空闲状态保存失败，请重试。' },
}, true, true);

export default i18n;
