import { getLocales } from 'expo-localization';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const deviceLanguage = getLocales()[0]?.languageCode;

// eslint-disable-next-line import/no-named-as-default-member
void i18n.use(initReactI18next).init({
  compatibilityJSON: 'v4',
  fallbackLng: 'en',
  lng: deviceLanguage === 'it' || deviceLanguage === 'zh' ? deviceLanguage : 'en',
  interpolation: { escapeValue: false },
  resources: {
    en: { translation: { now: 'Now', map: 'Map', create: 'Create', chats: 'Orbits', me: 'Me', tryAgain: 'Try again', home: { nearby: 'Nearby now', hero: 'Meet people.\nDo something. Now.', subtitle: 'Spontaneous plans nearby, for the next six hours.', free: "I'm free", forming: "See what's forming nearby", plans: 'Plans near you', seeMap: 'See map' }, location: { title: 'Find plans around you', privacy: 'HAO uses your area only for distance and nearby search. People never see your live location.', use: 'Use my location', retry: 'Try location again', settings: 'Open settings', manual: 'or browse without location' }, orbit: { eyebrow: 'ORBIT', title: 'Your circles', subtitle: "Coordinate plans you're attending.", loadError: "Orbits couldn't load", emptyTitle: 'No active Orbits yet', emptyBody: 'Attend a nearby plan to open a temporary group.', discover: "See what's happening", chatReady: 'Plan chat is ready' }, profile: { title: 'Me', demoMode: 'Testing channel · browse-only', activityTitle: 'Your real-world activity', activityNotRecorded: 'Activity is not recorded in test mode.', statsLoadError: 'Activity could not load. Please try again.', successfulMeets: 'Successful Meets', plansCheckedIn: 'Plans checked in', meetExplanation: 'A Successful Meet requires at least two valid check-ins and a completed plan.', accountPrivacy: 'Account and privacy', deleteDescription: 'Deleting your account permanently removes your profile and associated personal data.', deleteAccount: 'Delete account', deleting: 'Deleting…', exitTest: 'Exit test mode', signOut: 'Sign out', deleteTitle: 'Delete account?', deleteBody: 'This permanently deletes your HAO account, profile, messages, memberships, and activity. This cannot be undone.', cancel: 'Cancel', deleteConfirm: 'Delete permanently', deleteError: 'Your account could not be deleted. Please try again.' } } },
    it: { translation: { now: 'Ora', map: 'Mappa', create: 'Crea', chats: 'Gruppi', me: 'Profilo', tryAgain: 'Riprova', home: { nearby: 'Vicino a te', hero: 'Incontra persone.\nFai qualcosa. Ora.', subtitle: 'Programmi spontanei nelle vicinanze per le prossime sei ore.', free: 'Sono libero', forming: 'Scopri cosa si sta formando', plans: 'Programmi vicino a te', seeMap: 'Vedi mappa' }, location: { title: 'Trova programmi vicino a te', privacy: 'HAO usa solo la tua zona per distanza e ricerca. Nessuno vede la tua posizione in tempo reale.', use: 'Usa la mia posizione', retry: 'Riprova posizione', settings: 'Apri impostazioni', manual: 'oppure esplora senza posizione' }, orbit: { eyebrow: 'GRUPPI', title: 'I tuoi gruppi', subtitle: 'Organizza i programmi a cui partecipi.', loadError: 'Impossibile caricare i gruppi', emptyTitle: 'Nessun gruppo attivo', emptyBody: 'Partecipa a un programma vicino per aprire un gruppo temporaneo.', discover: 'Scopri cosa succede', chatReady: 'La chat del programma è pronta' }, profile: { title: 'Profilo', demoMode: 'Canale di prova · sola navigazione', activityTitle: 'La tua attività nel mondo reale', activityNotRecorded: 'Le attività non vengono registrate in modalità di prova.', statsLoadError: 'Impossibile caricare le attività. Riprova.', successfulMeets: 'Incontri riusciti', plansCheckedIn: 'Programmi con check-in', meetExplanation: 'Un incontro riuscito richiede almeno due check-in validi e un programma completato.', accountPrivacy: 'Account e privacy', deleteDescription: 'Eliminando il tuo account rimuoverai definitivamente il profilo e i dati personali associati.', deleteAccount: 'Elimina account', deleting: 'Eliminazione…', exitTest: 'Esci dalla modalità di prova', signOut: 'Esci', deleteTitle: 'Eliminare l’account?', deleteBody: 'Questa azione elimina definitivamente il tuo account HAO, il profilo, i messaggi, le partecipazioni e le attività. Non può essere annullata.', cancel: 'Annulla', deleteConfirm: 'Elimina definitivamente', deleteError: 'Impossibile eliminare l’account. Riprova.' } } },
    zh: { translation: { now: '现在', map: '地图', create: '创建', chats: '群聊', me: '我的', tryAgain: '重试', home: { nearby: '附近动态', hero: '认识新朋友。\n现在就出发。', subtitle: '发现附近六小时内的即时活动。', free: '我有空', forming: '看看附近正在组什么局', plans: '附近计划', seeMap: '查看地图' }, location: { title: '查找附近计划', privacy: 'HAO 只使用大致区域计算距离和搜索，其他人永远看不到你的实时位置。', use: '使用我的位置', retry: '重试定位', settings: '打开设置', manual: '或不使用定位直接浏览' }, orbit: { eyebrow: '群聊', title: '你的群聊', subtitle: '协调你正在参加的计划。', loadError: '群聊暂时无法加载', emptyTitle: '暂无进行中的群聊', emptyBody: '参加附近的计划后，会自动建立临时群聊。', discover: '看看附近有什么', chatReady: '计划群聊已开启' }, profile: { title: '我的', demoMode: '测试模式 · 仅供浏览', activityTitle: '你的线下活动', activityNotRecorded: '测试模式不会记录活动数据。', statsLoadError: '活动数据暂时无法加载，请重试。', successfulMeets: '成功见面', plansCheckedIn: '已签到计划', meetExplanation: '“成功见面”需要至少两名成员有效签到，且计划已完成。', accountPrivacy: '账号与隐私', deleteDescription: '删除账号会永久移除你的个人资料及相关个人数据。', deleteAccount: '删除账号', deleting: '正在删除…', exitTest: '退出测试模式', signOut: '退出登录', deleteTitle: '删除账号？', deleteBody: '此操作会永久删除你的 HAO 账号、个人资料、消息、成员记录和活动数据，且无法恢复。', cancel: '取消', deleteConfirm: '永久删除', deleteError: '无法删除账号，请重试。' } } },
  },
});

export default i18n;
