create schema if not exists extensions;
create extension if not exists postgis with schema extensions;
create extension if not exists pgcrypto with schema extensions;

create type public.plan_status as enum ('draft', 'open', 'confirmed', 'full', 'started', 'completed', 'cancelled');
create type public.plan_source as enum ('user', 'system', 'merchant');
create type public.member_status as enum ('joined', 'left', 'removed', 'no_show');
create type public.message_type as enum ('text', 'system', 'quick_action');
create type public.report_status as enum ('open', 'reviewing', 'resolved', 'dismissed');
create type public.intent_status as enum ('active', 'matched', 'expired', 'cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text check (char_length(display_name) between 1 and 60),
  avatar_url text,
  birth_date date,
  primary_language text,
  onboarding_completed boolean not null default false,
  is_suspended boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.interests (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  label text not null
);

create table public.profile_interests (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  interest_id bigint not null references public.interests(id) on delete cascade,
  primary key (profile_id, interest_id)
);

create table public.profile_languages (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  language_code text not null,
  primary key (profile_id, language_code)
);

create table public.venues (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  address text,
  location extensions.geography(point, 4326) not null,
  source text,
  external_place_id text,
  is_public_place boolean not null default true,
  created_at timestamptz not null default now()
);

create index venues_location_gix on public.venues using gist(location);

create table public.plans (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid references public.profiles(id) on delete set null,
  activity_type text not null,
  title text not null check (char_length(title) between 1 and 120),
  note text check (note is null or char_length(note) <= 1000),
  venue_id uuid references public.venues(id) on delete set null,
  location extensions.geography(point, 4326) not null,
  starts_at timestamptz not null,
  expected_end_at timestamptz,
  min_participants integer not null default 2 check (min_participants >= 2),
  max_participants integer not null default 4 check (max_participants >= min_participants),
  confirmation_deadline timestamptz,
  status public.plan_status not null default 'open',
  source public.plan_source not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expected_end_at is null or expected_end_at > starts_at),
  check (confirmation_deadline is null or confirmation_deadline <= starts_at)
);

create index plans_location_gix on public.plans using gist(location);
create index plans_starts_at_idx on public.plans(starts_at);
create index plans_status_starts_idx on public.plans(status, starts_at);
create index plans_creator_idx on public.plans(creator_id);

create table public.plan_interests (
  plan_id uuid not null references public.plans(id) on delete cascade,
  interest_id bigint not null references public.interests(id) on delete cascade,
  primary key (plan_id, interest_id)
);

create table public.plan_members (
  plan_id uuid not null references public.plans(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('creator', 'member')),
  status public.member_status not null default 'joined',
  joined_at timestamptz not null default now(),
  checked_in_at timestamptz,
  left_at timestamptz,
  primary key (plan_id, user_id)
);

create index plan_members_user_idx on public.plan_members(user_id, status);
create index plan_members_plan_status_idx on public.plan_members(plan_id, status);

create table public.availability_intents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  starts_at timestamptz not null default now(),
  expires_at timestamptz not null,
  location extensions.geography(point, 4326) not null,
  max_distance_m integer not null default 5000 check (max_distance_m between 100 and 50000),
  status public.intent_status not null default 'active',
  created_at timestamptz not null default now(),
  check (expires_at > starts_at)
);

create index availability_intents_location_gix on public.availability_intents using gist(location);
create index availability_intents_active_idx on public.availability_intents(status, expires_at);
create index availability_intents_user_idx on public.availability_intents(user_id, status);

create table public.intent_interests (
  intent_id uuid not null references public.availability_intents(id) on delete cascade,
  interest_id bigint not null references public.interests(id) on delete cascade,
  primary key (intent_id, interest_id)
);

create table public.plan_messages (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.plans(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  message_type public.message_type not null default 'text',
  body text not null check (char_length(body) between 1 and 2000),
  source_language text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index plan_messages_plan_created_idx on public.plan_messages(plan_id, created_at);
create index plan_messages_sender_idx on public.plan_messages(sender_id);

create table public.content_translations (
  id uuid primary key default gen_random_uuid(),
  content_type text not null check (content_type in ('plan_title', 'plan_note', 'message')),
  content_id uuid not null,
  source_language text,
  target_language text not null,
  source_hash text not null,
  translated_text text not null,
  provider text not null,
  model text not null,
  created_at timestamptz not null default now(),
  unique (content_type, content_id, target_language, source_hash)
);

create table public.ai_usage_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  plan_id uuid references public.plans(id) on delete set null,
  feature text not null,
  provider text not null,
  model text not null,
  request_id text,
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  cached_input_tokens integer not null default 0 check (cached_input_tokens >= 0),
  estimated_cost_usd numeric(14, 8) not null default 0 check (estimated_cost_usd >= 0),
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  cache_hit boolean not null default false,
  success boolean not null default true,
  error_code text,
  created_at timestamptz not null default now()
);

create index ai_usage_logs_created_idx on public.ai_usage_logs(created_at);
create index ai_usage_logs_feature_idx on public.ai_usage_logs(feature, created_at);
create index ai_usage_logs_plan_idx on public.ai_usage_logs(plan_id, created_at);
create index ai_usage_logs_user_idx on public.ai_usage_logs(user_id, created_at);

create table public.ai_feature_limits (
  feature text primary key,
  enabled boolean not null default true,
  daily_budget_usd numeric(12, 4),
  monthly_budget_usd numeric(12, 4),
  max_calls_per_user_per_day integer,
  model_key text not null,
  updated_at timestamptz not null default now(),
  check (daily_budget_usd is null or daily_budget_usd >= 0),
  check (monthly_budget_usd is null or monthly_budget_usd >= 0),
  check (max_calls_per_user_per_day is null or max_calls_per_user_per_day >= 0)
);

create table public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);
create index blocks_blocked_idx on public.blocks(blocked_id, blocker_id);

create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  target_type text not null check (target_type in ('user', 'plan', 'message')),
  target_id uuid not null,
  reason text not null,
  details text,
  status public.report_status not null default 'open',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null
);
create index reports_reporter_idx on public.reports(reporter_id, created_at);
create index reports_queue_idx on public.reports(status, created_at);

create table public.device_push_tokens (
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null,
  token text not null,
  last_seen_at timestamptz not null default now(),
  primary key (user_id, token)
);

create table public.successful_meets (
  plan_id uuid primary key references public.plans(id) on delete cascade,
  checked_in_members integer not null check (checked_in_members >= 2),
  qualified_at timestamptz not null default now()
);

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function private.set_updated_at();
create trigger plans_set_updated_at before update on public.plans
for each row execute function private.set_updated_at();
create trigger ai_feature_limits_set_updated_at before update on public.ai_feature_limits
for each row execute function private.set_updated_at();

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (new.id, nullif(new.raw_user_meta_data ->> 'name', ''), new.raw_user_meta_data ->> 'avatar_url');
  return new;
end;
$$;

revoke execute on function private.handle_new_user() from public, anon, authenticated;
create trigger on_auth_user_created after insert on auth.users
for each row execute function private.handle_new_user();
